### ISSUE TITLE
Feature request for translations

### ISSUE THREAD

**Issue by milotype** [ImEditor/imeditor.github.io#2]
Please think about using a translation platform like [Weblate](https://weblate.org) (which is my favorite) or some other, depending upon what suits your project best for [ImEditor](https://github.com/ImEditor/ImEditor) and for the [ImEditor website](https://github.com/ImEditor/imeditor.github.io).

It would be great if the website would automatically use the user's locale settings to show the page in the appropriate language ... and would greatly improve the internationalization of the app/project ...

I know this implies more work on the progrmming side, but maybe you have the time for it ... (unfortunately I'm just a translator, not a programmer, so I can't help you with it ...)

**Comment by Huluti** [comment]
Hello! I'm sorry but I don't have time anymore to work on ImEditor :/ I haven't done any update since one year.
I think the best option now is to use Drawing: https://flathub.org/apps/details/com.github.maoschanz.drawing

I will surely archive this repo soon.

**Comment by milotype** [comment]
OK, thank you.
